### PR TITLE
Selectfield: enables regex for default, fix #496

### LINKED ISSUE #496: Select default option uses regex for images/files
When specifying a select type for images in a page, specifying the filename + extension works perfect as a default option, but it would be nice to be able to have some regex/pattern matching for filenames or extensions. For example:

``` yaml
feature_image:
  label: Feature Image
  type: select
  options: images
  # this currently works
  default: feature.jpg 
  # this would be nice to have
  default: feature.*
```

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Wow, this goes pretty far. I'm not sure it's a bit too much. What's your opinion?

**Comment by distantnative** [comment]
Yea, I agree that it might be too much. Also could create some weird bugs depending on option values? Maybe instead of a regex, only allow to wildcard file extensions with `.*`?

**Comment by adamcbrewer** [comment]
I realise now that submitting the original issue with 'regex' is a bit over the top – @distantnative's suggestion for wildcard matching is much less aggressive and still serves the purpose.

**Comment by distantnative** [comment]
I will close this for now, as looking again at it I really think it's overpowered. Will try to come up with a less aggressive solution when the time permits it.

**Pull request closed without merging**
