### PR TITLE
Sort subpages on the dashboard

### PR DESCRIPTION
**Pull request by iksi**
Sort subpages on the dashboard according to blueprint settings in `site.php`

### CODE REVIEW

**Comment by iksi** [comment]
Fixed.

**Comment by bastianallgeier** [comment]
Ups, sorry! I totally missed your PR. Your version is actually a bit cleaner than mine *doh* :)

**Comment by iksi** [comment]
Being a bit more verbose sometimes doesn’t hurt though :)

**Comment by bastianallgeier** [comment]
I need to refactor quite some stuff in the panel anyway, so the spring cleaning will finally get it all in line I hope :)

**Pull request closed without merging**
