### PR TITLE
add more fieldoptions: show the visible or invisible root folders in …

### PR DESCRIPTION
**Pull request by handfix**
An easy way to show all visible or invisible root folders in a blueprint query select.

### CODE REVIEW

**Comment by AugustMiller** [comment]
Nice! This is something I'd been curious about— In the past, I'd tried to use `/` or `site` for the `page` property within a `query`. No dice.

Looks good!

**Comment by handfix** [comment]
That was exactly my approach as my problem "I need the freakin root folders" arised - without luck. So I patched it in...

**Comment by distantnative** [comment]
I haven't had the time to look at this closer, but I'd still feel much better to rather get `page: /` working instead of introducing options like `visibleRoot` - I'll try to take a closer look these days.

**Comment by bastianallgeier** [comment]
Though super late to the party (as always) I agree with @distantnative here. I just implemented this by enabling page: / to be set in query options. I think this is really a cleaner way to do this. But thanks for the PR and please excuse the super long delay.

**Pull request closed without merging**
