### PR TITLE
Tags Field: Fixed custom separator, fix #759

### LINKED ISSUE #759: Tags field: Custom separator only after saving
When setting a custom separator (e.g. `separator: ;` or `separator: /`) text input only gets converted to tags on save (split by the separator) when typing the separator, the text string is not converted immediately.

### PR DESCRIPTION
**Pull request by distantnative**
`keypress` was added since the keyCode on `keydown` can be different to what `charCodeAt()` will provide for a custom separator (e.g. `;`) while `keypress` will. Fix #759

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Did you have time to check this in various browsers? I'm a bit hesitant with this PR.

**Comment by distantnative** [comment]
Yes, but I agree, I'm myself still sceptical with using keydown and keypress. Maybe I can do some reading to figure out which one or which combination is really working cross-browser.

**Comment by distantnative** [comment]
Okay, Firefox was making some troubles. Added a more robust solution. Sadly it's quite a mess which browser does not support which part of keydown, keypress, keyCode and/or charCode.

**Comment by Thiousi** [comment]
I would love to see this fix merged :)

**Comment by distantnative** [comment]
Will become obsolete with Kirby 3

**Pull request closed without merging**
