### PR TITLE
Store: Reset if content file got modified

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
We shouldn't use model->modified here, but really check for changes in the text file.

**Comment by distantnative** [comment]
Using now `f::modified($this->structure->model()->textfile())`

**Comment by bastianallgeier** [comment]
Sounds good. We probably need to take care of multilang issues and user models don't have a textfile method yet. Maybe we should add it to make it consistent.

**Comment by distantnative** [comment]
Something like:

```php
if(multilang and is_a(model, 'Page/File')) {
  textfile(null, currentSelectedLanguage);
} else {
  textfile()
}
```

?

**Comment by bastianallgeier** [comment]
I just double-checked the page::textfile method in the multilang branch and I think we should be good by passing nothing. I already made it smart enough to take the current language if nothing is passed.

**Comment by distantnative** [comment]
Just checked multilang and it works there as well. Caught and fixed a small error if no textfile exists (which left me with the question if `f::modified` should not already catch that error?).

**Comment by bastianallgeier** [comment]
You are right! f::modified should catch that. I will fix that in the toolkit.

**Pull request merged**
