### PR TITLE
Made more error messages translatable

### PR DESCRIPTION
**Pull request by distantnative**
Some are still missing that incorporate variables. Maybe we should find a way to work with some kind of placeholders in language strings.

Maybe something like:

'language.string' => 'This file is {{1}} px wide and {{2}} big'

and then

l('language.string', array(300, '12 Kb'))

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Yes, sounds useful!! We should clean up language files in general. There are so many duplicates in there.

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by bastianallgeier** [comment]
yikes, there have been some bugs in the en and de language files after the PR. Please make sure to test your changes before you submit them.

**Comment by distantnative** [comment]
Urghs, realized that I did test it not with my develop setup but my other local starterkit (obviously without the changes). Sorry, stupid me today :persevere:

**Comment by lukasbestle** [comment]
I have been using the MessageFormat syntax for a project quite recently. It allows using easy plural rules, number and date formatting based on language rules and different output based on gender. I'm very happy with this syntax so far, as it takes away a lot of complexity from the localization.

PHP provides the [MessageFormatter class](http://php.net/manual/de/class.messageformatter.php), so we could also integrate it into Kirby.

**Pull request merged**
