### PR TITLE
More complete NL (Dutch) translation

### PR DESCRIPTION
**Pull request by gerardkd**
With support for the Kirby 2.1.0 tags / labels and with a more informal tone.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Hey! I'm a bit confused about the multiple dutch versions in the PRs. Could you guys somehow check which way to go: https://github.com/getkirby/panel/pull/509

**Comment by TECHMAUS** [comment]
I'd say they're both not wrong, but I prefer this one above #509 because it's a bit more consequent in the informal tone and contains some translations I prefer above the ones in #509.

**Comment by lekkerduidelijk** [comment]
Yes, take the #485 version. I didn't see this commit before. Sorry about that.

**Comment by gerardkd** [comment]
No problem!

**Comment by bastianallgeier** [comment]
With the move to Transifex I finally added this :) Thanks for your help!! It would be great to see you on Transifex again. It's actually much easier to translate stuff there than it has been here on Github. https://www.transifex.com/getkirby/panel/

**Comment by afbora** [comment]
:+1: I had propose Transifex to you. But I gave up for you're looking free services :)

**Pull request closed without merging**
