### PR TITLE
Textarea: Enable tab key insert, fix #363

### LINKED ISSUE #363: Allow tab key insertion of tab characters in textarea fields
This would be particularly useful for those of us who write a lot of code examples in markdown.

First approach is to create a new textarea field blueprint option allowing users to use the tab key to insert tab characters. Perhaps:

```
text:
    label: Content
    type: textarea
    tab: insert
```

Alternatively, create a key combination shortcut. Less intuitive to use but you could then avoid an extra blueprint option and make it as default behaviour. Perhaps match Safari's `Control` + `Alt` + `Tab`.

Overriding browser default behaviour is pretty simple, although most scripts neglect a polished Undo/Redo history.

Simple examples:
- [jQuery](http://stackoverflow.com/a/9951048)
- [Vanilla JS](http://jsfiddle.net/2wAzx/13)

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
As @jaydenseric writes in his example, I think it would be necessary to bind this to an option in the blueprint. By default the tabs key shouldn't be blocked by such a feature, as it will break keyboard navigation within the form.

**Comment by distantnative** [comment]
Will add one :+1:

**Comment by distantnative** [comment]
Works as an option now: `tabs: true`

**Comment by bastianallgeier** [comment]
I finally had the time to check this out. There are a couple questions. 

1. should it really insert a tab or rather spaces? I know this question would start a war in some nerd camps, but I seriously wonder if a tab is really useful here. 

2. It would be fantastic if Shift+Tab would outdent (is that a word) as in other editors, but I think it's quite advanced stuff. 

3. Maybe Alt+Tab could be assigned to jump out of the textarea. That way we would still maintain the keyboard accessibility of other fields. 

Otherwise, this seems really excellent. Especially with the option.

**Comment by distantnative** [comment]
Sounds good. Will try to add it – just about 1) I do not mind but also do not have an opinion on this. How about spaces and the option defines how many?

```
tabs: false
tabs: 2
tabs: 4
```

**Comment by bastianallgeier** [comment]
sounds perfect to me :) I think for web stuff spaces are always preferable, because the output is more reliable.

**Comment by distantnative** [comment]
Added all 3 things:

- Enabling/Disabling the tab feature with
```
tabs: false
tabs: 2
tabs: 4
```

- Then tab will ident by the specified number of spaces
- Shift + Tab will outdent (only if the right number of spaces is right before the current cursor position)
- Alt + Tab will jump out.

Seems to work cross-browser except the last part - alt + tab does not work for me in Firefox.

**Pull request closed without merging**
