### PR TITLE
Input character counter

### PR DESCRIPTION
**Pull request by iksi**
A counter for the input field that uses the min/max validate values. See https://forum.getkirby.com/t/panel-character-count-word-count/1504 and my original repo http://github.com/iksi/KirbyInputField

I’ve made this pull request becaus @lukasbestle suggested it could be part of the core. I originally made it as I use restrictrions on character count and when you do so it is usefull to give the panel users a visual cue that these restrictions are in place.

screenshot

### CODE REVIEW

**Comment by lukasbestle** [comment]
Thanks for the pull request. I think it needs to be independent from the validation constraints though. The counter would only be displayed if enabled by a separate option. If the min/max constraints are not set, it would simply display the current character count.

Also: I have not tested this, but doesn't implementing this for the `input` field add a counter to e.g. checkbox fields?

**Comment by iksi** [comment]
True, I made it this way because the counter for me is mainly of importance when there are restrictions in place on the field length. You’re right, there is a counter added to checkbox field when a validate option is given (just noticed this). A simple check could be used if the field type is a checkbox `$this->type() === 'checkbox'` to not use the counter I guess.

**Comment by lukasbestle** [comment]
If you implement a separate option, the checkbox issue doesn't matter (because no one would enable that option).

I think that this feature is very flexible with a separate option. The original use case for Jens was to have a counter to see how much you have written. The maximum wouldn't be a hard limit in this case, so you wouldn't need to bind it to the validation constraint.

**Comment by distantnative** [comment]
>You’re right, there is a counter added to checkbox field when a validate option is given (just noticed this). A simple check could be used if the field type is a checkbox $this->type() === 'checkbox' to not use the counter I guess.

Shouldn't it modify the `text` field instead of the `input` field in this case?

**Comment by lukasbestle** [comment]
No, then it won't be available to the `textarea` field.

**Comment by iksi** [comment]
It’s probably a better place for it. I do use it on textarea fields as well though (for instance for a description field that I want to limit) which would mean the counter needs to be added to both of those fields.

**Comment by distantnative** [comment]
@lukasbestle - true. But looking on the `textarea` field. Couldn't that one rather extend the `text` field anyways?

**Comment by lukasbestle** [comment]
That's actually very true.

**Comment by iksi** [comment]
> @lukasbestle - true. But looking on the textarea field. Couldn't that one rather extend the text field anyways?

In that case the `title` field should also extend the `text` field.

**Comment by distantnative** [comment]
>In that case the title field should also extend the text field.

It probably could. We'll see what @bastianallgeier thinks about it.

**Comment by bastianallgeier** [comment]
I really love this, but won't add it to 2.2, just to get this thing finally ready. I also just accepted @distantnative's PR to extend the text field with textareas instead of the input field. Would you mind adopting this for your PR?

**Comment by distantnative** [comment]
I just noticed that your PR is on the `master` branch. Could you please close this one and just recreate a PR to the `develop` branch instead. Thanks!

**Comment by iksi** [comment]
Added a new PR https://github.com/getkirby/panel/pull/640

**Pull request closed without merging**
