### PR TITLE
Files: filters dotfiles, fix #493

### LINKED ISSUE #493: Remove dotfiles from Site files list in sidebar
screen shot 2015-05-27 at 14 32 41

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Hmm, maybe we should add that to the core instead?

**Comment by distantnative** [comment]
To always remove dotfiles from files collections?

**Comment by adamcbrewer** [comment]
My feeling is that dotfiles are always project or system based and not really content, hence removing them from the panel views. Any reason to add them would be an edge case.

**Comment by distantnative** [comment]
Would you rather put it in the `files.php`:

```php
    foreach($inventory['files'] as $filename) {
      if(substr($filename, 0, 1) !== '.') {
        $file = new File($this, $filename);
        $this->data[strtolower($file->filename())] = $file;
      }
    }
```

Or extend the `page.php` around line number 294, where already some dotfiles are excluded:

```php
    $ignore = array('.', '..', '.DS_Store', '.git', '.svn', 'Thumb.db');
    $items  = array_diff(scandir($this->root), array_merge($ignore, (array)$this->kirby->option('content.file.ignore')));
```

?

**Comment by bastianallgeier** [comment]
I think we should ignore invisible files in general.

**Comment by distantnative** [comment]
Suggestion for the core to remove them in general: https://github.com/getkirby/kirby/pull/257

**Pull request closed without merging**
