### PR TITLE
Add character counter

### PR DESCRIPTION
**Pull request by iksi**
Add character counter to the TextField class.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I couldn't help and add it anyway :) Made some small changes but otherwise great work!!! Thank you so much for your ongoing support :+1:

**Comment by distantnative** [comment]
Not sure if really a problem or me just being too confused, but right now it looks to me as if we'd use both `$this->min` as well as `$this->validate[']` (same for `max`). Shouldn't it be rather just one of these?

**Comment by distantnative** [comment]
Also the css field asset could be removed now that @bastianallgeier included it in the panel form.css, couldn't it?

**Comment by iksi** [comment]
> Not sure if really a problem or me just being too confused, but right now it looks to me as if we'd use both `$this->min` as well as `$this->validate[]` (same for `max`). Shouldn't it be rather just one of these?

Couldn’t really find where `$this->min` and `$this->max` are getting set with the blueprint `validate` values.

**Comment by iksi** [comment]
> Also the css field asset could be removed now that @bastianallgeier included it in the panel form.css, couldn't it?

Yes, that can be removed now.

**Comment by distantnative** [comment]
I think it's a question if it should rather be

```
info:
  label: Info
  type: text
  min: 10
  max: 30
```

or

```
info:
  label: Info
  type: text
  validate:
    min: 10
    max: 30
```

**Comment by bastianallgeier** [comment]
I can't follow exactly with the min max thing. The css has to stay there though :) The gulp task is adding the css to the form.css automatically. So the css file for the field always stays the source of it.

**Comment by bastianallgeier** [comment]
Having min and max as direct options would of course make it more accessible, but also more confusing. Would those automatically set the validators? Could you overwrite them with validate then? I think it's more clear that way.

**Comment by distantnative** [comment]
> I can't follow exactly with the min max thing.

Right now, we set `min`and `max` as options at the same level as `label` and `type`: https://github.com/getkirby/panel/blob/develop/app/fields/text/text.php#L6-L7
And we use that for the field validation: https://github.com/getkirby/panel/blob/develop/app/fields/text/text.php#L25-L26

But for the counter we use `min` and `max` from
```
validate:
  min: 
  max:
```
https://github.com/getkirby/panel/blob/develop/app/fields/text/text.php#L32-L42

Seems redundant.

**Comment by bastianallgeier** [comment]
I totally missed that while working on it. We should clean that up. Do you want to do it or should I?

**Comment by distantnative** [comment]
I can do it. Should we go for the `validate` version then? IT's also how it's in the docs as it seems: http://getkirby.com/docs/cheatsheet/validators/min

Might be a little more code, but more explicit.

**Comment by bastianallgeier** [comment]
yes! go for it :)

**Comment by iksi** [comment]
👍🏼

**Pull request merged**
